/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC165UpgradeableContract } from "./ERC165Upgradeable";
import { ERC721UpgradeableContract } from "./ERC721Upgradeable";
import { IERC165UpgradeableContract } from "./IERC165Upgradeable";
import { IERC721EnumerableUpgradeableContract } from "./IERC721EnumerableUpgradeable";
import { IERC721MetadataUpgradeableContract } from "./IERC721MetadataUpgradeable";
import { IERC721ReceiverUpgradeableContract } from "./IERC721ReceiverUpgradeable";
import { IERC721UpgradeableContract } from "./IERC721Upgradeable";
import { MigrationsContract } from "./Migrations";
import { NFTTContract } from "./NFTT";
import { OwnableUpgradeableContract } from "./OwnableUpgradeable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC165Upgradeable"): ERC165UpgradeableContract;
      require(name: "ERC721Upgradeable"): ERC721UpgradeableContract;
      require(name: "IERC165Upgradeable"): IERC165UpgradeableContract;
      require(
        name: "IERC721EnumerableUpgradeable"
      ): IERC721EnumerableUpgradeableContract;
      require(
        name: "IERC721MetadataUpgradeable"
      ): IERC721MetadataUpgradeableContract;
      require(
        name: "IERC721ReceiverUpgradeable"
      ): IERC721ReceiverUpgradeableContract;
      require(name: "IERC721Upgradeable"): IERC721UpgradeableContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "NFTT"): NFTTContract;
      require(name: "OwnableUpgradeable"): OwnableUpgradeableContract;
    }
  }
}

export {
  ERC165UpgradeableContract,
  ERC165UpgradeableInstance,
} from "./ERC165Upgradeable";
export {
  ERC721UpgradeableContract,
  ERC721UpgradeableInstance,
} from "./ERC721Upgradeable";
export {
  IERC165UpgradeableContract,
  IERC165UpgradeableInstance,
} from "./IERC165Upgradeable";
export {
  IERC721EnumerableUpgradeableContract,
  IERC721EnumerableUpgradeableInstance,
} from "./IERC721EnumerableUpgradeable";
export {
  IERC721MetadataUpgradeableContract,
  IERC721MetadataUpgradeableInstance,
} from "./IERC721MetadataUpgradeable";
export {
  IERC721ReceiverUpgradeableContract,
  IERC721ReceiverUpgradeableInstance,
} from "./IERC721ReceiverUpgradeable";
export {
  IERC721UpgradeableContract,
  IERC721UpgradeableInstance,
} from "./IERC721Upgradeable";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { NFTTContract, NFTTInstance } from "./NFTT";
export {
  OwnableUpgradeableContract,
  OwnableUpgradeableInstance,
} from "./OwnableUpgradeable";
